Dataset:
  train_data_dir: /local1/cfyang/substep_train
  eval_data_dir: /local1/cfyang/substep_valid_seen
  unseen_eval_data_dir: /local1/cfyang/substep_valid_unseen
Model:
  do_sample: False
Training:
  output_dir: /local1/cfyang/output/subpolicy/pretrain_bert_meta
  evaluation_strategy: epoch
  learning_rate: 0.0001
  warmup_ratio: 0.2
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  num_train_epochs: 20
  weight_decay: 0.0001
  logging_steps: 20
  save_steps: 1000
  report_to: tensorboard
  ddp_find_unused_parameters: False
  dataloader_drop_last: True
Misc:
  pretrain_weight: bert-base-uncased
